//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : RentaVideojuegos
	/// Data Source    : .\SQLEXPRESS
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class RentaVideojuegosDB : LinqToDB.Data.DataConnection
	{
		public ITable<Alquiler>   Alquilers    { get { return this.GetTable<Alquiler>(); } }
		public ITable<Bitacora>   Bitacoras    { get { return this.GetTable<Bitacora>(); } }
		public ITable<Jugador>    Jugadors     { get { return this.GetTable<Jugador>(); } }
		public ITable<Sucursal>   Sucursals    { get { return this.GetTable<Sucursal>(); } }
		public ITable<Videojuego> Videojuegoes { get { return this.GetTable<Videojuego>(); } }

		public RentaVideojuegosDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RentaVideojuegosDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RentaVideojuegosDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RentaVideojuegosDB(DataOptions<RentaVideojuegosDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Alquiler")]
	public partial class Alquiler
	{
		[Column("idAlquiler"),        PrimaryKey,  Identity] public int       IdAlquiler        { get; set; } // int
		[Column("idJugador"),         NotNull              ] public int       IdJugador         { get; set; } // int
		[Column("idVideojuego"),      NotNull              ] public int       IdVideojuego      { get; set; } // int
		[Column("fechaInicio"),       NotNull              ] public DateTime  FechaInicio       { get; set; } // datetime
		[Column("fechaDevolucion"),   NotNull              ] public DateTime  FechaDevolucion   { get; set; } // datetime
		[Column("totalDiasAlquiler"), NotNull              ] public int       TotalDiasAlquiler { get; set; } // int
		[Column("costoPorDia"),       NotNull              ] public decimal   CostoPorDia       { get; set; } // numeric(10, 2)
		[Column("costoTotal"),        NotNull              ] public decimal   CostoTotal        { get; set; } // numeric(14, 2)
		[Column("fechaCreacion"),     NotNull              ] public DateTime  FechaCreacion     { get; set; } // datetime
		[Column("fechaModificacion"),    Nullable          ] public DateTime? FechaModificacion { get; set; } // datetime
		[Column("estado"),            NotNull              ] public char      Estado            { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Alquiler_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdAlquiler", OtherKey="IdAlquiler", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Alquiler_Jugador (dbo.Jugador)
		/// </summary>
		[Association(ThisKey="IdJugador", OtherKey="IdJugador", CanBeNull=false)]
		public Jugador Jugador { get; set; }

		/// <summary>
		/// FK_Alquiler_Videojuego (dbo.Videojuego)
		/// </summary>
		[Association(ThisKey="IdVideojuego", OtherKey="IdVideojuego", CanBeNull=false)]
		public Videojuego Videojuego { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Bitacora")]
	public partial class Bitacora
	{
		[Column("idBitacora"),      PrimaryKey, Identity] public int      IdBitacora      { get; set; } // int
		[Column("idAlquiler"),      NotNull             ] public int      IdAlquiler      { get; set; } // int
		[Column("idJugador"),       NotNull             ] public int      IdJugador       { get; set; } // int
		[Column("accionRealizada"), NotNull             ] public string   AccionRealizada { get; set; } // varchar(25)
		[Column("fechaDeLaAccion"), NotNull             ] public DateTime FechaDeLaAccion { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_Bitacora_Alquiler (dbo.Alquiler)
		/// </summary>
		[Association(ThisKey="IdAlquiler", OtherKey="IdAlquiler", CanBeNull=false)]
		public Alquiler Alquiler { get; set; }

		/// <summary>
		/// FK_Bitacora_Jugador (dbo.Jugador)
		/// </summary>
		[Association(ThisKey="IdJugador", OtherKey="IdJugador", CanBeNull=false)]
		public Jugador Jugador { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Jugador")]
	public partial class Jugador
	{
		[Column("idJugador"),       PrimaryKey, Identity] public int    IdJugador       { get; set; } // int
		[Column("nombreCompleto"),  NotNull             ] public string NombreCompleto  { get; set; } // varchar(250)
		[Column("email"),           NotNull             ] public string Email           { get; set; } // varchar(150)
		[Column("clave"),           NotNull             ] public string Clave           { get; set; } // varchar(15)
		[Column("esAdministrador"), NotNull             ] public bool   EsAdministrador { get; set; } // bit
		[Column("estado"),          NotNull             ] public char   Estado          { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Alquiler_Jugador_BackReference (dbo.Alquiler)
		/// </summary>
		[Association(ThisKey="IdJugador", OtherKey="IdJugador", CanBeNull=true)]
		public IEnumerable<Alquiler> Alquilers { get; set; }

		/// <summary>
		/// FK_Bitacora_Jugador_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdJugador", OtherKey="IdJugador", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Sucursal")]
	public partial class Sucursal
	{
		[Column("idSucursal"),  PrimaryKey,  Identity] public int     IdSucursal  { get; set; } // int
		[Column("nombre"),      NotNull              ] public string  Nombre      { get; set; } // varchar(150)
		[Column("direccion"),      Nullable          ] public string  Direccion   { get; set; } // varchar(500)
		[Column("telefono"),       Nullable          ] public string  Telefono    { get; set; } // varchar(20)
		[Column("costoPorDia"), NotNull              ] public decimal CostoPorDia { get; set; } // numeric(10, 2)
		[Column("estado"),      NotNull              ] public char    Estado      { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Videojuego_Sucursal_BackReference (dbo.Videojuego)
		/// </summary>
		[Association(ThisKey="IdSucursal", OtherKey="IdSucursal", CanBeNull=true)]
		public IEnumerable<Videojuego> Videojuegoes { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Videojuego")]
	public partial class Videojuego
	{
		[Column("idVideojuego"),     PrimaryKey,  Identity] public int      IdVideojuego     { get; set; } // int
		[Column("idSucursal"),       NotNull              ] public int      IdSucursal       { get; set; } // int
		[Column("titulo"),           NotNull              ] public string   Titulo           { get; set; } // varchar(100)
		[Column("descripcion"),      NotNull              ] public string   Descripcion      { get; set; } // varchar(500)
		[Column("idCategoria"),      NotNull              ] public string   IdCategoria      { get; set; } // varchar(100)
		[Column("fechaLanzamiento"), NotNull              ] public DateTime FechaLanzamiento { get; set; } // date
		[Column("desarrolladora"),   NotNull              ] public string   Desarrolladora   { get; set; } // varchar(100)
		[Column("distribuidora"),    NotNull              ] public string   Distribuidora    { get; set; } // varchar(100)
		[Column("imagen"),              Nullable          ] public string   Imagen           { get; set; } // varchar(255)
		[Column("trailer"),             Nullable          ] public string   Trailer          { get; set; } // varchar(255)
		[Column("estado"),           NotNull              ] public char     Estado           { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Alquiler_Videojuego_BackReference (dbo.Alquiler)
		/// </summary>
		[Association(ThisKey="IdVideojuego", OtherKey="IdVideojuego", CanBeNull=true)]
		public IEnumerable<Alquiler> Alquilers { get; set; }

		/// <summary>
		/// FK_Videojuego_Sucursal (dbo.Sucursal)
		/// </summary>
		[Association(ThisKey="IdSucursal", OtherKey="IdSucursal", CanBeNull=false)]
		public Sucursal Sucursal { get; set; }

		#endregion
	}

	public static partial class RentaVideojuegosDBStoredProcedures
	{
		#region SpCancelarAlquiler

		public static IEnumerable<SpCancelarAlquilerResult> SpCancelarAlquiler(this RentaVideojuegosDB dataConnection, int? @idAlquiler, int? @idJugadorSesion)
		{
			var parameters = new []
			{
				new DataParameter("@idAlquiler",      @idAlquiler,      LinqToDB.DataType.Int32),
				new DataParameter("@idJugadorSesion", @idJugadorSesion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpCancelarAlquilerResult>("[dbo].[sp_CancelarAlquiler]", parameters);
		}

		public partial class SpCancelarAlquilerResult
		{
			[Column("idAlquiler")     ] public int?   IdAlquiler      { get; set; }
			[Column("accionRealizada")] public string AccionRealizada { get; set; }
		}

		#endregion

		#region SpContarAlquileresActivosPorVideojuego

		public static IEnumerable<SpContarAlquileresActivosPorVideojuegoResult> SpContarAlquileresActivosPorVideojuego(this RentaVideojuegosDB dataConnection, int? @idVideojuego)
		{
			var parameters = new []
			{
				new DataParameter("@idVideojuego", @idVideojuego, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpContarAlquileresActivosPorVideojuegoResult>("[dbo].[sp_ContarAlquileresActivosPorVideojuego]", parameters);
		}

		public partial class SpContarAlquileresActivosPorVideojuegoResult
		{
			[Column("cantidad")] public int? Cantidad { get; set; }
		}

		#endregion

		#region SpCrearAlquiler

		public static IEnumerable<SpCrearAlquilerResult> SpCrearAlquiler(this RentaVideojuegosDB dataConnection, int? @idJugador, int? @idSucursal, DateTime? @fechaInicio, DateTime? @fechaDevolucion, int? @idJugadorSesion)
		{
			var parameters = new []
			{
				new DataParameter("@idJugador",       @idJugador,       LinqToDB.DataType.Int32),
				new DataParameter("@idSucursal",      @idSucursal,      LinqToDB.DataType.Int32),
				new DataParameter("@fechaInicio",     @fechaInicio,     LinqToDB.DataType.DateTime),
				new DataParameter("@fechaDevolucion", @fechaDevolucion, LinqToDB.DataType.DateTime),
				new DataParameter("@idJugadorSesion", @idJugadorSesion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpCrearAlquilerResult>("[dbo].[sp_CrearAlquiler]", parameters);
		}

		public partial class SpCrearAlquilerResult
		{
			[Column("idAlquiler")       ] public int?     IdAlquiler        { get; set; }
			[Column("idVideojuego")     ] public int?     IdVideojuego      { get; set; }
			[Column("totalDiasAlquiler")] public int?     TotalDiasAlquiler { get; set; }
			[Column("costoPorDia")      ] public decimal? CostoPorDia       { get; set; }
			[Column("costoTotal")       ] public decimal? CostoTotal        { get; set; }
		}

		#endregion

		#region SpCrearVideojuego

		public static IEnumerable<SpCrearVideojuegoResult> SpCrearVideojuego(this RentaVideojuegosDB dataConnection, int? @idSucursal, string @titulo, string @descripcion, string @idCategoria, DateTime? @fechaLanzamiento, string @desarrolladora, string @distribuidora, string @imagen, string @trailer)
		{
			var parameters = new []
			{
				new DataParameter("@idSucursal",       @idSucursal,       LinqToDB.DataType.Int32),
				new DataParameter("@titulo",           @titulo,           LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				},
				new DataParameter("@idCategoria",      @idCategoria,      LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@fechaLanzamiento", @fechaLanzamiento, LinqToDB.DataType.Date),
				new DataParameter("@desarrolladora",   @desarrolladora,   LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@distribuidora",    @distribuidora,    LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@imagen",           @imagen,           LinqToDB.DataType.VarChar)
				{
					Size = 255
				},
				new DataParameter("@trailer",          @trailer,          LinqToDB.DataType.VarChar)
				{
					Size = 255
				}
			};

			return dataConnection.QueryProc<SpCrearVideojuegoResult>("[dbo].[sp_CrearVideojuego]", parameters);
		}

		public partial class SpCrearVideojuegoResult
		{
			[Column("idVideojuego")] public decimal? IdVideojuego { get; set; }
		}

		#endregion

		#region SpInactivarVideojuego

		public static IEnumerable<SpInactivarVideojuegoResult> SpInactivarVideojuego(this RentaVideojuegosDB dataConnection, int? @idVideojuego)
		{
			var parameters = new []
			{
				new DataParameter("@idVideojuego", @idVideojuego, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpInactivarVideojuegoResult>("[dbo].[sp_InactivarVideojuego]", parameters);
		}

		public partial class SpInactivarVideojuegoResult
		{
			[Column("idVideojuego")] public int?   IdVideojuego { get; set; }
			[Column("resultado")   ] public string Resultado    { get; set; }
		}

		#endregion

		#region SpModificarAlquiler

		public static IEnumerable<SpModificarAlquilerResult> SpModificarAlquiler(this RentaVideojuegosDB dataConnection, int? @idAlquiler, DateTime? @fechaInicio, DateTime? @fechaDevolucion, int? @idJugadorSesion)
		{
			var parameters = new []
			{
				new DataParameter("@idAlquiler",      @idAlquiler,      LinqToDB.DataType.Int32),
				new DataParameter("@fechaInicio",     @fechaInicio,     LinqToDB.DataType.DateTime),
				new DataParameter("@fechaDevolucion", @fechaDevolucion, LinqToDB.DataType.DateTime),
				new DataParameter("@idJugadorSesion", @idJugadorSesion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpModificarAlquilerResult>("[dbo].[sp_ModificarAlquiler]", parameters);
		}

		public partial class SpModificarAlquilerResult
		{
			[Column("idAlquiler")       ] public int?     IdAlquiler        { get; set; }
			[Column("totalDiasAlquiler")] public int?     TotalDiasAlquiler { get; set; }
			[Column("costoPorDia")      ] public decimal? CostoPorDia       { get; set; }
			[Column("costoTotal")       ] public decimal? CostoTotal        { get; set; }
		}

		#endregion

		#region SpModificarVideojuego

		public static IEnumerable<SpModificarVideojuegoResult> SpModificarVideojuego(this RentaVideojuegosDB dataConnection, int? @idVideojuego, string @titulo, string @descripcion, string @idCategoria, DateTime? @fechaLanzamiento, string @desarrolladora, string @distribuidora, string @imagen, string @trailer)
		{
			var parameters = new []
			{
				new DataParameter("@idVideojuego",     @idVideojuego,     LinqToDB.DataType.Int32),
				new DataParameter("@titulo",           @titulo,           LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				},
				new DataParameter("@idCategoria",      @idCategoria,      LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@fechaLanzamiento", @fechaLanzamiento, LinqToDB.DataType.Date),
				new DataParameter("@desarrolladora",   @desarrolladora,   LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@distribuidora",    @distribuidora,    LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@imagen",           @imagen,           LinqToDB.DataType.VarChar)
				{
					Size = 255
				},
				new DataParameter("@trailer",          @trailer,          LinqToDB.DataType.VarChar)
				{
					Size = 255
				}
			};

			return dataConnection.QueryProc<SpModificarVideojuegoResult>("[dbo].[sp_ModificarVideojuego]", parameters);
		}

		public partial class SpModificarVideojuegoResult
		{
			[Column("idVideojuego")] public int?   IdVideojuego { get; set; }
			[Column("resultado")   ] public string Resultado    { get; set; }
		}

		#endregion

		#region SpObtenerAlquileresPorJugador

		public static IEnumerable<SpObtenerAlquileresPorJugadorResult> SpObtenerAlquileresPorJugador(this RentaVideojuegosDB dataConnection, int? @idJugador)
		{
			var parameters = new []
			{
				new DataParameter("@idJugador", @idJugador, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerAlquileresPorJugadorResult>("[dbo].[sp_ObtenerAlquileresPorJugador]", parameters);
		}

		public partial class SpObtenerAlquileresPorJugadorResult
		{
			[Column("idAlquiler")     ] public int      IdAlquiler      { get; set; }
			[Column("nombreCompleto") ] public string   NombreCompleto  { get; set; }
			[Column("nombreSucursal") ] public string   NombreSucursal  { get; set; }
			[Column("titulo")         ] public string   Titulo          { get; set; }
			[Column("fechaInicio")    ] public DateTime FechaInicio     { get; set; }
			[Column("fechaDevolucion")] public DateTime FechaDevolucion { get; set; }
			[Column("costoTotal")     ] public decimal  CostoTotal      { get; set; }
			[Column("estado")         ] public char     Estado          { get; set; }
		}

		#endregion

		#region SpObtenerBitacoraPorAlquiler

		public static IEnumerable<SpObtenerBitacoraPorAlquilerResult> SpObtenerBitacoraPorAlquiler(this RentaVideojuegosDB dataConnection, int? @idAlquiler)
		{
			var parameters = new []
			{
				new DataParameter("@idAlquiler", @idAlquiler, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerBitacoraPorAlquilerResult>("[dbo].[sp_ObtenerBitacoraPorAlquiler]", parameters);
		}

		public partial class SpObtenerBitacoraPorAlquilerResult
		{
			[Column("idBitacora")     ] public int      IdBitacora      { get; set; }
			[Column("idAlquiler")     ] public int      IdAlquiler      { get; set; }
			[Column("nombreCompleto") ] public string   NombreCompleto  { get; set; }
			[Column("accionRealizada")] public string   AccionRealizada { get; set; }
			[Column("fechaDeLaAccion")] public DateTime FechaDeLaAccion { get; set; }
		}

		#endregion

		#region SpObtenerDetalleAlquiler

		public static IEnumerable<SpObtenerDetalleAlquilerResult> SpObtenerDetalleAlquiler(this RentaVideojuegosDB dataConnection, int? @idAlquiler)
		{
			var parameters = new []
			{
				new DataParameter("@idAlquiler", @idAlquiler, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerDetalleAlquilerResult>("[dbo].[sp_ObtenerDetalleAlquiler]", parameters);
		}

		public partial class SpObtenerDetalleAlquilerResult
		{
			[Column("idAlquiler")       ] public int      IdAlquiler        { get; set; }
			[Column("idJugador")        ] public int      IdJugador         { get; set; }
			[Column("nombreCompleto")   ] public string   NombreCompleto    { get; set; }
			[Column("idSucursal")       ] public int      IdSucursal        { get; set; }
			[Column("nombreSucursal")   ] public string   NombreSucursal    { get; set; }
			[Column("idVideojuego")     ] public int      IdVideojuego      { get; set; }
			[Column("titulo")           ] public string   Titulo            { get; set; }
			[Column("fechaInicio")      ] public DateTime FechaInicio       { get; set; }
			[Column("fechaDevolucion")  ] public DateTime FechaDevolucion   { get; set; }
			[Column("totalDiasAlquiler")] public int      TotalDiasAlquiler { get; set; }
			[Column("costoPorDia")      ] public decimal  CostoPorDia       { get; set; }
			[Column("costoTotal")       ] public decimal  CostoTotal        { get; set; }
			[Column("estado")           ] public char     Estado            { get; set; }
		}

		#endregion

		#region SpObtenerJugadoresActivos

		public static IEnumerable<SpObtenerJugadoresActivosResult> SpObtenerJugadoresActivos(this RentaVideojuegosDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerJugadoresActivosResult>("[dbo].[sp_ObtenerJugadoresActivos]");
		}

		public partial class SpObtenerJugadoresActivosResult
		{
			[Column("idJugador")     ] public int    IdJugador      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
		}

		#endregion

		#region SpObtenerSucursalesActivas

		public static IEnumerable<SpObtenerSucursalesActivasResult> SpObtenerSucursalesActivas(this RentaVideojuegosDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerSucursalesActivasResult>("[dbo].[sp_ObtenerSucursalesActivas]");
		}

		public partial class SpObtenerSucursalesActivasResult
		{
			[Column("idSucursal") ] public int     IdSucursal  { get; set; }
			[Column("nombre")     ] public string  Nombre      { get; set; }
			[Column("costoPorDia")] public decimal CostoPorDia { get; set; }
		}

		#endregion

		#region SpObtenerTodosAlquileres

		public static IEnumerable<SpObtenerTodosAlquileresResult> SpObtenerTodosAlquileres(this RentaVideojuegosDB dataConnection, int? @idJugador, DateTime? @fechaInicio, DateTime? @fechaDevolucion)
		{
			var parameters = new []
			{
				new DataParameter("@idJugador",       @idJugador,       LinqToDB.DataType.Int32),
				new DataParameter("@fechaInicio",     @fechaInicio,     LinqToDB.DataType.DateTime),
				new DataParameter("@fechaDevolucion", @fechaDevolucion, LinqToDB.DataType.DateTime)
			};

			return dataConnection.QueryProc<SpObtenerTodosAlquileresResult>("[dbo].[sp_ObtenerTodosAlquileres]", parameters);
		}

		public partial class SpObtenerTodosAlquileresResult
		{
			[Column("idAlquiler")     ] public int      IdAlquiler      { get; set; }
			[Column("nombreCompleto") ] public string   NombreCompleto  { get; set; }
			[Column("nombreSucursal") ] public string   NombreSucursal  { get; set; }
			[Column("titulo")         ] public string   Titulo          { get; set; }
			[Column("fechaInicio")    ] public DateTime FechaInicio     { get; set; }
			[Column("fechaDevolucion")] public DateTime FechaDevolucion { get; set; }
			[Column("costoTotal")     ] public decimal  CostoTotal      { get; set; }
			[Column("estado")         ] public char     Estado          { get; set; }
		}

		#endregion

		#region SpObtenerVideojuegoPorId

		public static IEnumerable<SpObtenerVideojuegoPorIdResult> SpObtenerVideojuegoPorId(this RentaVideojuegosDB dataConnection, int? @idVideojuego)
		{
			var parameters = new []
			{
				new DataParameter("@idVideojuego", @idVideojuego, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerVideojuegoPorIdResult>("[dbo].[sp_ObtenerVideojuegoPorId]", parameters);
		}

		public partial class SpObtenerVideojuegoPorIdResult
		{
			[Column("idVideojuego")    ] public int      IdVideojuego     { get; set; }
			[Column("idSucursal")      ] public int      IdSucursal       { get; set; }
			[Column("nombreSucursal")  ] public string   NombreSucursal   { get; set; }
			[Column("titulo")          ] public string   Titulo           { get; set; }
			[Column("descripcion")     ] public string   Descripcion      { get; set; }
			[Column("idCategoria")     ] public string   IdCategoria      { get; set; }
			[Column("fechaLanzamiento")] public DateTime FechaLanzamiento { get; set; }
			[Column("desarrolladora")  ] public string   Desarrolladora   { get; set; }
			[Column("distribuidora")   ] public string   Distribuidora    { get; set; }
			[Column("imagen")          ] public string   Imagen           { get; set; }
			[Column("trailer")         ] public string   Trailer          { get; set; }
			[Column("estado")          ] public char     Estado           { get; set; }
		}

		#endregion

		#region SpObtenerVideojuegos

		public static IEnumerable<SpObtenerVideojuegosResult> SpObtenerVideojuegos(this RentaVideojuegosDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerVideojuegosResult>("[dbo].[sp_ObtenerVideojuegos]");
		}

		public partial class SpObtenerVideojuegosResult
		{
			[Column("idVideojuego")  ] public int    IdVideojuego   { get; set; }
			[Column("nombreSucursal")] public string NombreSucursal { get; set; }
			[Column("titulo")        ] public string Titulo         { get; set; }
			[Column("idCategoria")   ] public string IdCategoria    { get; set; }
			[Column("estado")        ] public char   Estado         { get; set; }
		}

		#endregion

		#region SpObtenerVideojuegosPorSucursal

		public static IEnumerable<SpObtenerVideojuegosPorSucursalResult> SpObtenerVideojuegosPorSucursal(this RentaVideojuegosDB dataConnection, int? @idSucursal)
		{
			var parameters = new []
			{
				new DataParameter("@idSucursal", @idSucursal, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerVideojuegosPorSucursalResult>("[dbo].[sp_ObtenerVideojuegosPorSucursal]", parameters);
		}

		public partial class SpObtenerVideojuegosPorSucursalResult
		{
			[Column("idVideojuego")    ] public int      IdVideojuego     { get; set; }
			[Column("titulo")          ] public string   Titulo           { get; set; }
			[Column("descripcion")     ] public string   Descripcion      { get; set; }
			[Column("idCategoria")     ] public string   IdCategoria      { get; set; }
			[Column("fechaLanzamiento")] public DateTime FechaLanzamiento { get; set; }
			[Column("desarrolladora")  ] public string   Desarrolladora   { get; set; }
			[Column("distribuidora")   ] public string   Distribuidora    { get; set; }
			[Column("imagen")          ] public string   Imagen           { get; set; }
			[Column("trailer")         ] public string   Trailer          { get; set; }
			[Column("estado")          ] public char     Estado           { get; set; }
		}

		#endregion

		#region SpValidarCredenciales

		public static IEnumerable<SpValidarCredencialesResult> SpValidarCredenciales(this RentaVideojuegosDB dataConnection, string @email, string @clave)
		{
			var parameters = new []
			{
				new DataParameter("@email", @email, LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@clave", @clave, LinqToDB.DataType.VarChar)
				{
					Size = 15
				}
			};

			return dataConnection.QueryProc<SpValidarCredencialesResult>("[dbo].[sp_ValidarCredenciales]", parameters);
		}

		public partial class SpValidarCredencialesResult
		{
			[Column("idJugador")      ] public int    IdJugador       { get; set; }
			[Column("nombreCompleto") ] public string NombreCompleto  { get; set; }
			[Column("email")          ] public string Email           { get; set; }
			[Column("esAdministrador")] public bool   EsAdministrador { get; set; }
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Alquiler Find(this ITable<Alquiler> table, int IdAlquiler)
		{
			return table.FirstOrDefault(t =>
				t.IdAlquiler == IdAlquiler);
		}

		public static Bitacora Find(this ITable<Bitacora> table, int IdBitacora)
		{
			return table.FirstOrDefault(t =>
				t.IdBitacora == IdBitacora);
		}

		public static Jugador Find(this ITable<Jugador> table, int IdJugador)
		{
			return table.FirstOrDefault(t =>
				t.IdJugador == IdJugador);
		}

		public static Sucursal Find(this ITable<Sucursal> table, int IdSucursal)
		{
			return table.FirstOrDefault(t =>
				t.IdSucursal == IdSucursal);
		}

		public static Videojuego Find(this ITable<Videojuego> table, int IdVideojuego)
		{
			return table.FirstOrDefault(t =>
				t.IdVideojuego == IdVideojuego);
		}
	}
}
